In [1]:
import pandas as pd
import json
import numpy as np

## Importing Most Followed Streamer Data Set

In [2]:
mfstream = pd.read_csv('./data/Most_Followers_three_days.csv')

In [3]:
mfstream.head(2)

,Unnamed: 0,Channel,Watch time,Stream time,Peak viewers,Average viewers,Followers,Followers gained,Views gained,Partnered,Mature,Language
0,0,Ninja,8214510,720,15570,10949,16469658,11911,436545,True,False,English
1,1,Tfue,24031665,1680,53438,13240,9742302,22439,616332,True,False,English

In [4]:
mfstream = mfstream.drop(columns = ['Unnamed: 0'])

In [5]:
mfstream.head()

,Channel,Watch time,Stream time,Peak viewers,Average viewers,Followers,Followers gained,Views gained,Partnered,Mature,Language
0,Ninja,8214510,720,15570,10949,16469658,11911,436545,True,False,English
1,Tfue,24031665,1680,53438,13240,9742302,22439,616332,True,False,English
2,shroud,27108015,1230,30920,17825,8609552,11195,626494,True,False,English
3,Myth,1612470,390,5603,4134,7076540,872,66656,True,False,English
4,pokimane,10662570,600,31844,19896,6715772,30149,559517,True,False,English

In [6]:
mfstream.to_csv('./data/Most_Followers_Cleaned.csv')

## Importing Most Watched Streamer Data set

In [7]:
mwstream = pd.read_csv('./data/most_watched_streamers.csv')

In [8]:
mwstream.head()

,Unnamed: 0,Unnamed: 1,Channel,Watch time,Stream time,Peak viewers,Average viewers,Followers,Followers gained,Views gained,Partnered,Mature,Language,Unnamed: 13
0,https://static-cdn.jtvnw.net/jtv_user_pictures...,1,ibai,132391320,1050,261328,117179,4177020,78874,4437941,True,False,Spanish,ibai
1,https://static-cdn.jtvnw.net/jtv_user_pictures...,2,xQcOW,106420740,1785,75989,59552,4389067,25487,1566960,True,False,English,xQcOW
2,https://static-cdn.jtvnw.net/jtv_user_pictures...,3,Asmongold,97432065,1455,126200,68182,1848011,21662,1945478,True,False,English,Asmongold
3,https://static-cdn.jtvnw.net/jtv_user_pictures...,4,Gaules,88518180,4290,92951,20642,2248735,11206,1248532,True,True,Portuguese,Gaules
4,https://static-cdn.jtvnw.net/jtv_user_pictures...,5,limit_maximum,88386420,2415,75970,36852,201005,19677,1431397,True,False,English,limit_maximum

In [9]:
mwstream = mwstream.drop(columns = ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 13'])

In [10]:
mwstream.head()

,Channel,Watch time,Stream time,Peak viewers,Average viewers,Followers,Followers gained,Views gained,Partnered,Mature,Language
0,ibai,132391320,1050,261328,117179,4177020,78874,4437941,True,False,Spanish
1,xQcOW,106420740,1785,75989,59552,4389067,25487,1566960,True,False,English
2,Asmongold,97432065,1455,126200,68182,1848011,21662,1945478,True,False,English
3,Gaules,88518180,4290,92951,20642,2248735,11206,1248532,True,True,Portuguese
4,limit_maximum,88386420,2415,75970,36852,201005,19677,1431397,True,False,English

In [11]:
mwstream.to_csv('./data/most_watched_cleaned.csv')

## Importing Most Watched Games on Twitch

In [12]:
mwgames = pd.read_csv('./data/most_watched_games_twitch.csv')

In [13]:
mwgames.head()

,Unnamed: 0,Unnamed: 1,Game,Watch time,Stream time,Peak viewers,Peak channels,Streamers,Average viewers,Average channels,Average viewer ratio,Followers gained,Views gained,FPR,VPR,Unnamed: 15
0,Just Chatting,1,Just Chatting,1446634500,17181780,721587,5437,93519,334869,3977,84.20,1072995,33590391,3.746975,117.300039,Just Chatting
1,World of Warcraft,2,World of Warcraft,786294300,14728920,363789,7803,33932,182012,3409,53.38,167954,15715561,0.684181,64.019199,World of Warcraft
2,Call of Duty: Warzone,3,Call of Duty: Warzone,559050900,16582320,343398,7996,51623,129409,3838,33.71,291126,7899075,1.053385,28.581314,Call of Duty: Warzone
3,League of Legends,4,League of Legends,543214860,18853320,318449,6128,61174,125744,4364,28.81,261347,12300848,0.831727,39.146998,League of Legends
4,Fortnite,5,Fortnite,516702240,32494680,343767,12185,125201,119607,7521,15.90,934376,13650345,1.725284,25.204763,Fortnite

In [14]:
mwgames = mwgames.drop(columns = ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 15'])

In [15]:
mwgames.head()

,Game,Watch time,Stream time,Peak viewers,Peak channels,Streamers,Average viewers,Average channels,Average viewer ratio,Followers gained,Views gained,FPR,VPR
0,Just Chatting,1446634500,17181780,721587,5437,93519,334869,3977,84.20,1072995,33590391,3.746975,117.300039
1,World of Warcraft,786294300,14728920,363789,7803,33932,182012,3409,53.38,167954,15715561,0.684181,64.019199
2,Call of Duty: Warzone,559050900,16582320,343398,7996,51623,129409,3838,33.71,291126,7899075,1.053385,28.581314
3,League of Legends,543214860,18853320,318449,6128,61174,125744,4364,28.81,261347,12300848,0.831727,39.146998
4,Fortnite,516702240,32494680,343767,12185,125201,119607,7521,15.90,934376,13650345,1.725284,25.204763

In [16]:
mwgames.to_csv('./data/most_watched_games_cleaned.csv')

## YT data

In [17]:
with open('./data/ytdataset.json', "rb") as f: 
    ytd = json.load(f)

In [18]:
ytd = pd.DataFrame(ytd)

In [19]:
ytd.shape

(575610, 26)

In [20]:
ytd.head()

,totalviews/channelelapsedtime,channelId,videoCategoryId,channelViewCount,likes/subscriber,views/subscribers,videoCount,subscriberCount,videoId,dislikes/views,...,comments/views,totvideos/videocount,elapsedtime,videoLikeCount,videoDislikeCount,dislikes/subscriber,totviews/totsubs,views/elapsedtime,videoPublished,VideoCommentCount
0,0.16519925596076884,UCdzU3DSGzyWzN2118yd9X9g,22,14654,0.5555555555555556,95.11111111111111,30,18,--DwgB78t-c,0.0005841121495327102,...,0.0,488.46666666666664,50040,10,1,0.05555555555555555,814.1111111111111,0.03421262989608313,2012-01-19T18:38:28.000Z,0
1,1.1338200815767217,UC0UnhAG47DRyVZGVcbhAXhQ,10,105909,0.2391304347826087,59.32608695652174,51,184,--NZRkXBV7k,0.00027482594356907294,...,0.00018321729571271528,2076.6470588235293,22080,44,3,0.016304347826086956,575.5923913043479,0.4943840579710145,2015-03-30T04:04:40.000Z,2
2,0.6681201550387597,UCXjtAvK5P3wXBGh0vbGylzg,27,48265,0.023668639053254437,10.289940828402367,72,338,--hoQ2sGG4M,0.0002875215641173088,...,0.0005750431282346176,670.3472222222222,71544,8,1,0.0029585798816568047,142.7958579881657,0.04861344067986134,2009-08-07T06:51:10.000Z,2
3,25.65350494473531,UCeKHMeUlcLNPLCLUfZUQI2w,26,2116722,0.007301256178858102,0.8841775883179901,172,22051,--sBoaqBlzA,0.00030773965225419295,...,0.0005128994204236549,12306.523255813954,54096,161,6,0.00027209650355992926,95.99210920139676,0.3604148181011535,2011-08-04T01:07:38.000Z,10
4,52.773777521761396,UCNWPDyaWf2eAHnofFLSnEMg,20,1649075,0.004545454545454545,10.004545454545454,2777,220,--7h1S4neDM,0.0,...,0.0,593.8332733165287,30120,1,0,0.0,7495.795454545455,0.07307436918990703,2014-04-29T15:44:44.000Z,0

In [21]:
ytnames = pd.read_csv('./data/YouTube_Names.csv')

In [22]:
ytnames.head()

                         Name                        ID
0                      Zee TV  UCppHT7SZKKvar4Oc9J4oljQ
1                    T-Series  UCq-Fj5jknLsUf-MWSy4_brA
2  Cocomelon - Nursery Rhymes  UCbCmjCuTUZos6Inko4u57UQ
3                   SET India  UCpEhnqL0y41EpW2TvWAHD7Q
4                         WWE  UCJ5v_MCY6GNUBTO8-D3XoAg

In [23]:
ytnames.shape

(4998, 2)

In [24]:
ytnames.columns

Index(['Name', ' ID'], dtype='object')

In [25]:
ytset = ytd.merge(ytnames, how = 'left', left_on = 'channelId', right_on = ' ID')

In [26]:
ytset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 575868 entries, 0 to 575867
Data columns (total 28 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   totalviews/channelelapsedtime  575868 non-null  object
 1   channelId                      575868 non-null  object
 2   videoCategoryId                575868 non-null  object
 3   channelViewCount               575868 non-null  object
 4   likes/subscriber               575868 non-null  object
 5   views/subscribers              575868 non-null  object
 6   videoCount                     575868 non-null  object
 7   subscriberCount                575868 non-null  object
 8   videoId                        575868 non-null  object
 9   dislikes/views                 575868 non-null  object
 10  channelelapsedtime             575868 non-null  object
 11  comments/subscriber            575868 non-null  object
 12  likes/views                    575868 non-null  object
 13  channelCommentCount            575868 non-null  object
 14  videoViewCount                 575868 non-null  object
 15  likes/dislikes                 575868 non-null  object
 16  comments/views                 575868 non-null  object
 17  totvideos/videocount           575868 non-null  object
 18  elapsedtime                    575868 non-null  object
 19  videoLikeCount                 575868 non-null  object
 20  videoDislikeCount              575868 non-null  object
 21  dislikes/subscriber            575868 non-null  object
 22  totviews/totsubs               575868 non-null  object
 23  views/elapsedtime              575868 non-null  object
 24  videoPublished                 575868 non-null  object
 25  VideoCommentCount              575868 non-null  object
 26  Name                           7419 non-null    object
 27   ID                            7419 non-null    object
dtypes: object(28)
memory usage: 127.4+ MB

In [27]:
ytset.isnull().sum()

totalviews/channelelapsedtime         0
channelId                             0
videoCategoryId                       0
channelViewCount                      0
likes/subscriber                      0
views/subscribers                     0
videoCount                            0
subscriberCount                       0
videoId                               0
dislikes/views                        0
channelelapsedtime                    0
comments/subscriber                   0
likes/views                           0
channelCommentCount                   0
videoViewCount                        0
likes/dislikes                        0
comments/views                        0
totvideos/videocount                  0
elapsedtime                           0
videoLikeCount                        0
videoDislikeCount                     0
dislikes/subscriber                   0
totviews/totsubs                      0
views/elapsedtime                     0
videoPublished                        0
VideoCommentCount                     0
Name                             568449
 ID                              568449
dtype: int64

In [28]:
ytset = ytset.dropna()

In [29]:
ytset.shape

(7419, 28)

In [30]:
ytset.head()

,totalviews/channelelapsedtime,channelId,videoCategoryId,channelViewCount,likes/subscriber,views/subscribers,videoCount,subscriberCount,videoId,dislikes/views,...,elapsedtime,videoLikeCount,videoDislikeCount,dislikes/subscriber,totviews/totsubs,views/elapsedtime,videoPublished,VideoCommentCount,Name,ID
145,64517.6623427673,UCHIwQiZhIn6fm5b_IilqBbQ,20,2790259861,0.0008368320621193652,0.01737325756332855,7345,5449122,--z-wc2jCvo,0.001257011270848958,...,21864,4560,119,2.183838056846589e-05,512.0567792389306,4.329903036955726,2015-04-08T14:30:01.000Z,118,DaniRep | +6 Vídeos Diarios De GTA…,UCHIwQiZhIn6fm5b_IilqBbQ
148,10492.026927937997,UCRxDTCmIjgli-Xgh2KPE9dA,1,1004475182,7.381393311801536e-05,0.06201354567688197,8897,609641,--HksGvyxzQ,5.2901655821827224e-05,...,45240,45,2,3.2806192496895715e-06,1647.6503089523178,0.8356763925729443,2012-08-07T10:32:51.000Z,4,シネマトゥデイ,UCRxDTCmIjgli-Xgh2KPE9dA
150,68005.0729377226,UCUtZaxDF3hD5VK4xRYFBePQ,24,5652037622,0.00017299969259569948,0.046673788055770764,1794,8109841,--79vjNYR6k,0.0008216275623023537,...,47448,1403,311,3.834847070367964e-05,696.935688628174,7.9775122239082785,2012-05-06T19:30:42.000Z,-1,Britain's Got Talent,UCUtZaxDF3hD5VK4xRYFBePQ
219,16456.980596111283,UCbu2SsF-Or3Rsn3NxqODImw,20,1658090166,0.00014123941150245208,0.003581988408381632,31042,2803750,--SbUSDNVM0,0.008463606492084039,...,34128,396,85,3.031654034774855e-05,591.3830284440481,0.29427449601500233,2013-11-12T20:00:04.000Z,97,GameSpot,UCbu2SsF-Or3Rsn3NxqODImw
390,4601.855376895652,UCTv-XvfzLX3i4IGWAm4sbmA,17,453048060,0.00017809472389693752,0.02318168411370067,28597,1600272,--CblQXFzYA,0.00024260721891258054,...,21936,285,9,5.624043912534869e-06,283.1069093254147,1.6911469730123998,2015-04-04T18:44:38.000Z,5,LaLiga Santander,UCTv-XvfzLX3i4IGWAm4sbmA

In [31]:
ytset = ytset.drop(columns = ['channelId', 'videoCategoryId', 'videoId', 'elapsedtime', 'videoPublished', 'likes/subscriber', 'views/subscribers',
                              'dislikes/views','comments/subscriber', 'dislikes/subscriber', 'totviews/totsubs', 'views/elapsedtime', 'comments/views'
                             , 'likes/dislikes', 'totalviews/channelelapsedtime', 'likes/views', 'totvideos/videocount'])

In [32]:
ytset.head()

,channelViewCount,videoCount,subscriberCount,channelelapsedtime,channelCommentCount,videoViewCount,videoLikeCount,videoDislikeCount,VideoCommentCount,Name,ID
145,2790259861,7345,5449122,43248,73,94669,4560,119,118,DaniRep | +6 Vídeos Diarios De GTA…,UCHIwQiZhIn6fm5b_IilqBbQ
148,1004475182,8897,609641,95737,125,37806,45,2,4,シネマトゥデイ,UCRxDTCmIjgli-Xgh2KPE9dA
150,5652037622,1794,8109841,83112,1961,378517,1403,311,-1,Britain's Got Talent,UCUtZaxDF3hD5VK4xRYFBePQ
219,1658090166,31042,2803750,100753,5119,10043,396,85,97,GameSpot,UCbu2SsF-Or3Rsn3NxqODImw
390,453048060,28597,1600272,98449,166,37097,285,9,5,LaLiga Santander,UCTv-XvfzLX3i4IGWAm4sbmA

In [34]:
ytset.shape

(7419, 11)

In [35]:
ytset.to_csv('./data/ytset_cleaned.csv')